package sn.sonatel.dsi.ins.imoc.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppServiceAllPropertiesEquals(AppService expected, AppService actual) {
        assertAppServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertAppServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppServiceAllUpdatablePropertiesEquals(AppService expected, AppService actual) {
        assertAppServiceUpdatableFieldsEquals(expected, actual);
        assertAppServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppServiceAutoGeneratedPropertiesEquals(AppService expected, AppService actual) {
        assertThat(expected)
            .as("Verify AppService auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppServiceUpdatableFieldsEquals(AppService expected, AppService actual) {
        assertThat(expected)
            .as("Verify AppService relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppServiceUpdatableRelationshipsEquals(AppService expected, AppService actual) {
        assertThat(expected)
            .as("Verify AppService relationships")
            .satisfies(e -> assertThat(e.getBusinessUnit()).as("check businessUnit").isEqualTo(actual.getBusinessUnit()))
            .satisfies(e -> assertThat(e.getDepartemen()).as("check departemen").isEqualTo(actual.getDepartemen()));
    }
}
