package sn.sonatel.dsi.ins.imoc.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssistantGWTEAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssistantGWTEAllPropertiesEquals(AssistantGWTE expected, AssistantGWTE actual) {
        assertAssistantGWTEAutoGeneratedPropertiesEquals(expected, actual);
        assertAssistantGWTEAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssistantGWTEAllUpdatablePropertiesEquals(AssistantGWTE expected, AssistantGWTE actual) {
        assertAssistantGWTEUpdatableFieldsEquals(expected, actual);
        assertAssistantGWTEUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssistantGWTEAutoGeneratedPropertiesEquals(AssistantGWTE expected, AssistantGWTE actual) {
        assertThat(expected)
            .as("Verify AssistantGWTE auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssistantGWTEUpdatableFieldsEquals(AssistantGWTE expected, AssistantGWTE actual) {
        assertThat(expected)
            .as("Verify AssistantGWTE relevant properties")
            .satisfies(e -> assertThat(e.getPhone()).as("check phone").isEqualTo(actual.getPhone()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssistantGWTEUpdatableRelationshipsEquals(AssistantGWTE expected, AssistantGWTE actual) {
        // empty method
    }
}
