package sn.sonatel.dsi.ins.imoc.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AttestationPresenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttestationPresenceAllPropertiesEquals(AttestationPresence expected, AttestationPresence actual) {
        assertAttestationPresenceAutoGeneratedPropertiesEquals(expected, actual);
        assertAttestationPresenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttestationPresenceAllUpdatablePropertiesEquals(AttestationPresence expected, AttestationPresence actual) {
        assertAttestationPresenceUpdatableFieldsEquals(expected, actual);
        assertAttestationPresenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttestationPresenceAutoGeneratedPropertiesEquals(AttestationPresence expected, AttestationPresence actual) {
        assertThat(expected)
            .as("Verify AttestationPresence auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttestationPresenceUpdatableFieldsEquals(AttestationPresence expected, AttestationPresence actual) {
        assertThat(expected)
            .as("Verify AttestationPresence relevant properties")
            .satisfies(e -> assertThat(e.getStartDate()).as("check startDate").isEqualTo(actual.getStartDate()))
            .satisfies(e -> assertThat(e.getEndDate()).as("check endDate").isEqualTo(actual.getEndDate()))
            .satisfies(e -> assertThat(e.getSignatureDate()).as("check signatureDate").isEqualTo(actual.getSignatureDate()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getComments()).as("check comments").isEqualTo(actual.getComments()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttestationPresenceUpdatableRelationshipsEquals(AttestationPresence expected, AttestationPresence actual) {
        assertThat(expected)
            .as("Verify AttestationPresence relationships")
            .satisfies(e -> assertThat(e.getAppUser()).as("check appUser").isEqualTo(actual.getAppUser()));
    }
}
