package sn.sonatel.dsi.ins.imoc.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BusinessUnitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUnitAllPropertiesEquals(BusinessUnit expected, BusinessUnit actual) {
        assertBusinessUnitAutoGeneratedPropertiesEquals(expected, actual);
        assertBusinessUnitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUnitAllUpdatablePropertiesEquals(BusinessUnit expected, BusinessUnit actual) {
        assertBusinessUnitUpdatableFieldsEquals(expected, actual);
        assertBusinessUnitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUnitAutoGeneratedPropertiesEquals(BusinessUnit expected, BusinessUnit actual) {
        assertThat(expected)
            .as("Verify BusinessUnit auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUnitUpdatableFieldsEquals(BusinessUnit expected, BusinessUnit actual) {
        assertThat(expected)
            .as("Verify BusinessUnit relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUnitUpdatableRelationshipsEquals(BusinessUnit expected, BusinessUnit actual) {
        // empty method
    }
}
