package sn.sonatel.dsi.ins.imoc.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DrhAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrhAllPropertiesEquals(Drh expected, Drh actual) {
        assertDrhAutoGeneratedPropertiesEquals(expected, actual);
        assertDrhAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrhAllUpdatablePropertiesEquals(Drh expected, Drh actual) {
        assertDrhUpdatableFieldsEquals(expected, actual);
        assertDrhUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrhAutoGeneratedPropertiesEquals(Drh expected, Drh actual) {
        assertThat(expected)
            .as("Verify Drh auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrhUpdatableFieldsEquals(Drh expected, Drh actual) {
        assertThat(expected)
            .as("Verify Drh relevant properties")
            .satisfies(e -> assertThat(e.getPhone()).as("check phone").isEqualTo(actual.getPhone()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrhUpdatableRelationshipsEquals(Drh expected, Drh actual) {
        // empty method
    }
}
