package sn.sonatel.dsi.ins.imoc.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RestaurationStagiaireAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRestaurationStagiaireAllPropertiesEquals(RestaurationStagiaire expected, RestaurationStagiaire actual) {
        assertRestaurationStagiaireAutoGeneratedPropertiesEquals(expected, actual);
        assertRestaurationStagiaireAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRestaurationStagiaireAllUpdatablePropertiesEquals(
        RestaurationStagiaire expected,
        RestaurationStagiaire actual
    ) {
        assertRestaurationStagiaireUpdatableFieldsEquals(expected, actual);
        assertRestaurationStagiaireUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRestaurationStagiaireAutoGeneratedPropertiesEquals(
        RestaurationStagiaire expected,
        RestaurationStagiaire actual
    ) {
        assertThat(expected)
            .as("Verify RestaurationStagiaire auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRestaurationStagiaireUpdatableFieldsEquals(RestaurationStagiaire expected, RestaurationStagiaire actual) {
        assertThat(expected)
            .as("Verify RestaurationStagiaire relevant properties")
            .satisfies(e -> assertThat(e.getStartDate()).as("check startDate").isEqualTo(actual.getStartDate()))
            .satisfies(e -> assertThat(e.getEndDate()).as("check endDate").isEqualTo(actual.getEndDate()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getCardNumber()).as("check cardNumber").isEqualTo(actual.getCardNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRestaurationStagiaireUpdatableRelationshipsEquals(
        RestaurationStagiaire expected,
        RestaurationStagiaire actual
    ) {
        assertThat(expected)
            .as("Verify RestaurationStagiaire relationships")
            .satisfies(e -> assertThat(e.getAppUser()).as("check appUser").isEqualTo(actual.getAppUser()));
    }
}
